export { default as ContactSection } from './Contact'
export { default as HeroSection } from './Home/Hero'
export { default as AboutSection } from './Home/About'
export { default as ServicesSection } from './Home/Services'
export { default as GallerySection } from './Home/Gallery'
